Added section on PID control for SO(2)
byu-magicc/lie_groups pull request #3
Opened 2018-06-18 22:45 UTC by dpkoch

2018-06-19 14:43 UTC, plusk01 requested changes
Two thoughts:

1. We have unofficially been targeting Python 3:
    - because it's probably the right thing to do
    - because Dr Beard is using Python 3

    In light of this, can you use `range` instead of `xrange` and integer division `//` instead of float division `/` (both in `Simulator.__init__`). [reference](http://python-future.org/compatible_idioms.html#division)

2. `SO2.wedge` vs `SO2.hat`: we briefly talked about this yesterday. I haven't seen the operator referred to as "wedge" before (other than LaTeX). I personally think we should use "hat" for consistency -- what do you think @jerelbn? It's at least popular enough to have made it on [Wikipedia](https://en.wikipedia.org/wiki/Rotation_group_SO(3)#Lie_algebra) (and in **bold**!)

2018-06-19 15:07 UTC, jerelbn commented
I prefer `hat` over `wedge`. I think it makes most sense to call it `skew` because that's what it is and I've seen several people call the reverse direction `vex`.

2018-06-19 16:56 UTC, jerelbn commented
The videos require `ffmpeg` so install instructions for it should be added to the readme.

2018-06-20 19:38 UTC, plusk01 approved these changes

2018-06-20 19:38 UTC, merged